apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: NodePort
  selector:
    app: ping-pong-app
  ports:
    - port: 3001 # Port in the cluster ## app door
      protocol: TCP
      targetPort: 3001 # Port your app is running on inside the container ## services internal door
      nodePort: 30001 # Port exposed on your machine

