apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:  
      labels:
        app: todo-app
    spec:  
      nodeSelector:
        kubernetes.io/hostname: k3d-mooc-agent-0
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: temibonn/todo-app:v1.1.3
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3000"
            - name: DOWNLOAD_DURATION
              value: "60"
