apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
spec:
  storageClassName: todo-app-pv 
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /usr/local
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-mooc-agent-0
