apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 3000 # Port in the cluster ## app door
      protocol: TCP
      targetPort: 3000 # Port your app is running on inside the container ## services internal door
