apiVersion: v1
kind: Service
metadata:
  name: log-output-ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: log-output-ping-pong
  ports:
    - name: log-output
      port: 2345
      protocol: TCP
      targetPort: 3000
    - name: ping-pong
      port: 3001
      protocol: TCP
      targetPort: 3001
